Repository wieslawsoltes/dxfinspect, pull requests merged in 2025-01, with the labels that each got.

#1 Tabbed view
  dxfInspect.Base/ViewModels/DxfMainViewModel.cs
  dxfInspect.Base/ViewModels/DxfTabViewModel.cs
  dxfInspect.Base/ViewModels/DxfTreeViewModel.cs
  dxfInspect.Base/Views/DxfMainView.axaml
  dxfInspect.Base/Views/DxfMainView.axaml.cs
  dxfInspect.Base/Views/DxfTreeView.axaml
  dxfInspect.Base/Views/DxfTreeView.axaml.cs
Labels: size/XL

#2 Improve filtering
  dxfInspect/Model/FilterOptions.cs
  dxfInspect/Model/TagModel.cs
  dxfInspect/ViewModels/DxfTreeViewModel.cs
  dxfInspect/Views/DxfTreeView.axaml
Labels: size/L

#3 Add size column
  dxfInspect/ViewModels/DxfTreeNodeViewModel.cs
  dxfInspect/ViewModels/DxfTreeViewModel.cs
Labels: size/M

#4 Optimize parser
  dxfInspect/Model/DxfRawTag.cs
  dxfInspect/Services/DxfParser.cs
  dxfInspect/Views/DxfMainView.axaml.cs
Labels: size/L

#5 Optimize filtering
  dxfInspect/Services/DxfRawTagCache.cs
  dxfInspect/ViewModels/DxfMainViewModel.cs
  dxfInspect/ViewModels/DxfTreeViewModel.cs
Labels: size/L

#6 Improve filters
  dxfInspect/ViewModels/DxfTreeNodeViewModel.cs
  dxfInspect/ViewModels/DxfTreeViewModel.cs
Labels: size/M

#7 Enable editing Code / Data
  dxfInspect/Services/DxfRawTagCache.cs
  dxfInspect/ViewModels/DxfTreeNodeViewModel.cs
  dxfInspect/ViewModels/DxfTreeViewModel.cs
  dxfInspect/Views/DxfTreeView.axaml
Labels: size/L

#8 Refactor to use Dynamic Data filtering
  src/dxfInspect/ViewModels/DxfMainViewModel.cs
  src/dxfInspect/ViewModels/DxfTabViewModel.cs
  src/dxfInspect/ViewModels/DxfTreeFiltersViewModel.cs
  src/dxfInspect/ViewModels/DxfTreeNodeViewModel.cs
  src/dxfInspect/ViewModels/DxfTreeViewModel.cs
  src/dxfInspect/Views/DxfTreeView.axaml
Labels: size/XXL

#9 Semi Theme: update most "X" buttons with icon button
  src/dxfInspect/Views/DxfMainView.axaml
  src/dxfInspect/Views/DxfTreeView.axaml
Labels: size/M
